import { ColorProps } from './interface';

export const colors: ColorProps = {
  primary: {
    'dumi-alita-color-primary': '#3880ff',
    'dumi-alita-color-primary-rgb': '56,128,255',
    'dumi-alita-color-primary-contrast': '#fff',
    'dumi-alita-color-primary-contrast-rgb': '255,255,255',
    'dumi-alita-color-primary-shade': '#3171e0',
    'dumi-alita-color-primary-tint': '#4c8dff',
  },
  secondary: {
    'dumi-alita-color-secondary': '#0cd1e8',
    'dumi-alita-color-secondary-rgb': '12,209,232',
    'dumi-alita-color-secondary-contrast': '#fff',
    'dumi-alita-color-secondary-contrast-rgb': '255,255,255',
    'dumi-alita-color-secondary-shade': '#0bb8cc',
    'dumi-alita-color-secondary-tint': '#24d6ea',
  },
  tertiary: {
    'dumi-alita-color-tertiary': '#7044ff',
    'dumi-alita-color-tertiary-rgb': '112,68,255',
    'dumi-alita-color-tertiary-contrast': '#fff',
    'dumi-alita-color-tertiary-contrast-rgb': '255,255,255',
    'dumi-alita-color-tertiary-shade': '#633ce0',
    'dumi-alita-color-tertiary-tint': '#7e57ff',
  },
  success: {
    'dumi-alita-color-success': '#10dc60',
    'dumi-alita-color-success-rgb': '16,220,96',
    'dumi-alita-color-success-contrast': '#fff',
    'dumi-alita-color-success-contrast-rgb': '255,255,255',
    'dumi-alita-color-success-shade': '#0ec254',
    'dumi-alita-color-success-tint': '#28e070',
  },
  warning: {
    'dumi-alita-color-warning': '#ffce00',
    'dumi-alita-color-warning-rgb': '255,206,0',
    'dumi-alita-color-warning-contrast': '#fff',
    'dumi-alita-color-warning-contrast-rgb': '255,255,255',
    'dumi-alita-color-warning-shade': '#e0b500',
    'dumi-alita-color-warning-tint': '#ffd31a',
  },
  danger: {
    'dumi-alita-color-danger': '#f04141',
    'dumi-alita-color-danger-rgb': '245,61,61',
    'dumi-alita-color-danger-contrast': '#fff',
    'dumi-alita-color-danger-contrast-rgb': '255,255,255',
    'dumi-alita-color-danger-shade': '#d33939',
    'dumi-alita-color-danger-tint': '#f25454',
  },
  dark: {
    'dumi-alita-color-dark': '#222428',
    'dumi-alita-color-dark-rgb': '34,34,34',
    'dumi-alita-color-dark-contrast': '#fff',
    'dumi-alita-color-dark-contrast-rgb': '255,255,255',
    'dumi-alita-color-dark-shade': '#1e2023',
    'dumi-alita-color-dark-tint': '#383a3e',
  },
  medium: {
    'dumi-alita-color-medium': '#989aa2',
    'dumi-alita-color-medium-rgb': '152,154,162',
    'dumi-alita-color-medium-contrast': '#fff',
    'dumi-alita-color-medium-contrast-rgb': '255,255,255',
    'dumi-alita-color-medium-shade': '#86888f',
    'dumi-alita-color-medium-tint': '#a2a4ab',
  },
  light: {
    'dumi-alita-color-light': '#f4f5f8',
    'dumi-alita-color-light-rgb': '244,244,244',
    'dumi-alita-color-light-contrast': '#000000',
    'dumi-alita-color-light-contrast-rgb': '0,0,0',
    'dumi-alita-color-light-shade': '#d7d8da',
    'dumi-alita-color-light-tint': '#f5f6f9',
  },
};
